### ISSUE TITLE
The data date cannot correspond to the precise orbital data

### ISSUE THREAD

**Issue by Arcyzr** [scottstanie/sentineleof#35] opened 2023-07-10 12:08 UTC
Hello Developer, I have encountered an issue while using the "eof" command to download the precise orbital data for Sentinel-1A descent data. I found that the date of the precise orbit downloaded is one day off from the data date, and they do not correspond exactly. For example, for a piece of descending data named "S1A_IW_SLC__1SDV_20180427T230513_20180427T230540_021659_02559D_B42D.zip", the date read by the program is "[INFO download.py] Downloading precise orbits for S1A on 2018-04-27". However, the precise orbital data downloaded using the "eof" command is "S1A_OPER_AUX_POEORB_OPOD_20210307T080522_V20180427T225942_20180429T005942.EOF", and the dates between them do not correspond. Meanwhile, I noticed that this error does not occur when downloading the Sentinel-1A ascending data, which I find very peculiar. Could you advise on how to resolve this issue?

**Comment by scottstanie** [comment] 2023-07-10 15:18
Hi, have you had any problems using the orbit file for your application? 
It looks like the orbit does cover the SAR acquisition: the orbit `start_time` is at  22:59, and the SAR acquisitions happened at 23:05 (using [this class](https://github.com/scottstanie/apertools/blob/56e7e5924f2f28948a7ac0fd99acab428c179421/apertools/parsers.py#L79)).

```python
In [1]: from apertools import parsers;  from rich import print

In [2]: print(parsers.Sentinel("S1A_IW_SLC__1SDV_20180427T230513_20180427T230540_021659_02559D_B42D.zip"))
Sentinel(
    filename='S1A_IW_SLC__1SDV_20180427T230513_20180427T230540_021659_02559D_B42D.zip',
    start_time=datetime.datetime(2018, 4, 27, 23, 5, 13, tzinfo=datetime.timezone.utc),
    stop_time=datetime.datetime(2018, 4, 27, 23, 5, 40, tzinfo=datetime.timezone.utc),
    relative_orbit=62,
    polarization='DV',
    mission='S1A'
)

In [3]: print(parsers.SentinelOrbit("S1A_OPER_AUX_POEORB_OPOD_20210307T080522_V20180427T225942_20180429T005942.EOF"))
SentinelOrbit(
    filename='S1A_OPER_AUX_POEORB_OPOD_20210307T080522_V20180427T225942_20180429T005942.EOF',
    orbit_type='precise',
    start_time=datetime.datetime(2018, 4, 27, 22, 59, 42, tzinfo=datetime.timezone.utc),
    stop_time=datetime.datetime(2018, 4, 29, 0, 59, 42, tzinfo=datetime.timezone.utc)
)
```

**Comment by scottstanie** [comment] 2023-07-11 14:56
Closing, but please reopen if you have some downstream error that is getting caused by this

**Closed by scottstanie** 2023-07-11 14:56 UTC
